### ISSUE TITLE
Double Cast issue

### ISSUE THREAD

**Issue by ubheamar** [bluemix/Gradient-Widgets#1]
Initializing gradle...                                       0.7s
Resolving dependencies...                                    1.7s
Running 'gradlew assembleRelease'...
compiler message: file:///C:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/gradient_widgets-0.3.0/lib/src/gradient_progress_indicator.dart:34:22: Error: A value of type 'dart.core::int' can't be assigned to a
 variable of type 'dart.core::double'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::double'.
compiler message:   double prevValue = 0;
compiler message:                      ^
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 428

* What went wrong:
Execution failed for task ':app:flutterBuildRelease'.
> Process 'command 'C:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s                                                                                                                                                                                                12.3s
Gradle build failed: 1

**Comment by ubheamar** [comment]
it should be 0.0

**Comment by bluemix** [comment]
although it builds successfully for the Android version, I also make the changes you mentioned and updated the library. 
thanks.
