### ISSUE TITLE
How to handle Dynamic width?

### ISSUE THREAD

**Issue by AkoWu101** [bluemix/Gradient-Widgets#10]
<img width="359" alt="螢幕截圖 2019-07-19 下午3 52 42" src="https://user-images.githubusercontent.com/2141985/61518962-5e1a0000-aa3d-11e9-8439-991c99f22ea7.png">

I built a horizontal list. When the button is disabled, i use outline button. When the button is enabled, i use gradient button. 

But, i found that the gradient button has limit width. How to set it to support dynamic width?

**Comment by nroehling** [comment]
got the same problem. Try it with:

increaseWidthBy: double.infinity

```
GradientButton(
                        child: Text('Anmelden'),
                        callback: () {},
                        gradient: Gradients.backToFuture,
                        shadowColor: Gradients.backToFuture.colors.last
                            .withOpacity(0.25),
                            increaseWidthBy: double.infinity,
                      ),
```

**Comment by bluemix** [comment]
@KingWu I hope @ecoparts provided a solution to your problem.

**Comment by ashskr1984** [comment]
facing same problem
![image](https://user-images.githubusercontent.com/5021214/124929797-67cc1200-e01e-11eb-86a4-1c2346e77bf4.png)
