### ISSUE TITLE
How to test GradientButton callback

### ISSUE THREAD

**Issue by Frezyx** [bluemix/Gradient-Widgets#18]
Hello. I use the GradientButton from your package. And action of it is callback function.
I write integration test for my application. How can i test it like a tap() on RaisedButton ?
![Group 2 (1)](https://user-images.githubusercontent.com/40857927/84810214-b1148280-b013-11ea-8d4a-4cc124b65334.jpg)

**Comment by bluemix** [comment]
I was having the same issue as yours by not finding the Widget from its value key.
You can solve by finding its type:
```dart
final SerializableFinder _authButton = find.byType('GradientButton');
```

Another way (currently I use) is by means of [Page Object Model](https://github.com/brianegan/flutter_architecture_samples/tree/master/integration_tests):
```dart
await _driver.runUnsynchronized(() async {
      await _driver.tap(_authButton);
});
```

However, I don't how if `find.byType('GradientButton');` will work if you have multiple buttons with the same type on the same view.

**Comment by Frezyx** [comment]
Thanks a lot for your response !
This helped in finding the element. But there are several of them on the screen, and Flutter responds with this error if on screen are more than one elements of this type.

![image 11](https://user-images.githubusercontent.com/40857927/84867158-692d4400-b083-11ea-89fa-6482bc0455f0.jpg)

Is there any other way to find it ?

**Comment by bluemix** [comment]
@Frezyx another solution is to try with text search (I am not sure it will click the button):
```dart
final SerializableFinder _authButton = find.text('Login');
```

Did you try this with a find by value-key?
```dart
await _driver.runUnsynchronized(() async {
      await _driver.tap(_authButton);
});
```

**Comment by Frezyx** [comment]
Unfortunately I've already tried it. Not working with my button :cry:
In any case, thank you for answering and suggesting a solution :blush: :thumbsup:
