### ISSUE TITLE
Not showing Ripple effect

### ISSUE THREAD

**Issue by danilo-medeiros** [bluemix/Gradient-Widgets#2]
How to enable ripple effect with CircularGradientButton widget?

**Comment by Huai-Dc** [comment]
> How to enable ripple effect with CircularGradientButton widget?

Have you dealt with this problem.

**Comment by bluemix** [comment]
Hello,
I don't want to show the ripple effect, because, those widgets are different to material design guidelines.
I'll try today another UI approach, by which it is clear when the user is touching the button.

**Comment by bluemix** [comment]
now, gradient buttons (CircularGradientButton and GradientButton) reacting (animating) to tap gestures (normal, up and down) 

![gradient_buttons_enhanced](https://user-images.githubusercontent.com/3332274/55656875-2d50ea80-5801-11e9-9044-ca75cc2c370d.gif)
