### ISSUE TITLE
GradientCard shape bug

### ISSUE THREAD

**Issue by ma-rp** [bluemix/Gradient-Widgets#6]
It appears to be a bug when trying to set a shape to the GradientCard object.
When trying to set the shape an exception is thrown on:
package:gradient_widgets/src/gradient_card.dart:37:27
The message is:
"exception was thrown: type 'RoundedRectangleBorder' is not a subtype of type 'Decoration'"

Reading the code this makes sense to me since the required type of GradientCard is ShapeBorder, and is trying to pass it as to the decoration argument of Container which is of the type Decoration.

**Comment by bluemix** [comment]
thanks for reporting the issue.
the problem is solved; I'll update the package either today or tomorrow.
