### ISSUE TITLE
GradientProgressIndicator uses the first color as a background color

### ISSUE THREAD

**Issue by ride4sun** [bluemix/Gradient-Widgets#8]
That might be a good default behavior but there should be a dedicated background. Maybe a gradient as well - probably both

**Comment by bluemix** [comment]
if it has a dedicated background color other than from the gradient, `GradientProgressIndicator` will be inconsistent. I mean, `GradientProgressIndicator`'s colors should be based upon the gradient it is assigned to it

**Comment by ride4sun** [comment]
Maybe the default is "as is" but there could be a setting which gives you the possibility to assign a gradient or color to redefine the default behavior. Thx.

**Comment by bluemix** [comment]
the background color should be extracted from the gradient colors.
i'll close this issue, unless a new method for picking a background color is provided.
